### PR TITLE
Replace `pc` by a `Makefile`

### PR DESCRIPTION
**Pull request by AntoineGagne**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

Something must be missing, though.

Because now, if I type `make` on the top-level directory, I get:

```text
/bin/sh: ./rebar: No such file or directory
make: *** [depends] Error 127
```

**Comment by jedisct1** [comment]
Could you possibly help fix the top Makefile?

If not, I'll have to revert that change.

**Comment by AntoineGagne** [comment]
Sorry, I have just seen your comment. I have sent out a PR (#2 ) to fix this

**Comment by jedisct1** [comment]
Thank you!

**Pull request merged**
